[build]
  base = "fitzgerald_restaurant"
  command = "gatsby build"
  functions = "netlify/functions"
  publish = "fitzgerald_restaurant/public"

[build.environment]
  GATSBY_ABAM_API_AVAILABLEDISH_URL = "https://app.aboireetamanger.fr/abam/apiavailabledish"
  GATSBY_ABAM_API_CONTACT_URL = "https://app.aboireetamanger.fr/abam/apicontact"
  GATSBY_ABAM_API_DISHTYPE_URL = "https://app.aboireetamanger.fr/abam/apidishtype"
  GATSBY_ABAM_API_DISH_URL = "https://app.aboireetamanger.fr/abam/apidish"
  GATSBY_ABAM_API_MENU_URL = "https://app.aboireetamanger.fr/abam/apimenu"
  GATSBY_ABAM_API_METEO_URL = "https://app.aboireetamanger.fr/abam/apimeteo"
  GATSBY_ABAM_API_REFRESH_INTERVAL = "60"
  GATSBY_GTAG = "ko"
  GATSBY_ABAM_MENU = "la-carte"
  NPM_CONFIG_USERCONFIG = ".npmrc-netlify"